comp/urls.py
from django.conf.urls import url
from . import views

app_name = 'questions'

urlpatterns = [
    # /comp/question
    url(r'^question/(?P<user_id>[0-9]+)/$', views.generate, name='generate'),
    # /comp/next_question/[question_id]
    url(r'^next_question/(?P<user_id>[0-9]+)/$', views.next, name='next'),
    # /comp/login
    url(r'^register/$', views.register, name='register'),
    # /comp/login/check_login
    url(r'^login/check_login/$', views.check_login, name='check_login'),
    # /comp/print_all_questions
    url(r'^print_all_questions/$',views.print_all_questions,name = 'print_all_questions'),
    # /comp/leaderboard/[user_id]
    url(r'^leaderboard/(?P<user_id>[0-9]+)/$', views.leaderboard, name='leaderboard'),
    url(r'^instruction_view/(?P<user_id>[0-9]+)/$', views.instruction_view, name='instruction_view'),

    url(r'^update/$', views.update_leaderboard, name='update_leaderboard')



]

cstrom/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^comp/', include('comp.urls')),

]

comp/models.py
from django.db import models


class Questions(models.Model):
    question = models.TextField(max_length=2000)
    option1 = models.CharField(max_length=300)
    option2 = models.CharField(max_length=300)
    option3 = models.CharField(max_length=300)
    option4 = models.CharField(max_length=300)
    answer = models.CharField(max_length=300)
    explanation = models.TextField(max_length=3000)

    def __str__(self):
        return str(self.pk)

    def get_options(self):
        return [self.option1, self.option2, self.option3, self.option4]


class User(models.Model):
    login_name = models.CharField(max_length=100)
    receipt_number = models.IntegerField()
    phone_number1 = models.IntegerField()
    phone_number2 = models.IntegerField()
    college_name1 = models.CharField(max_length=100)
    college_name2 = models.CharField(max_length=100)
    user_name1 = models.CharField(max_length=100)
    user_name2 = models.CharField(max_length=100)
    email1 = models.CharField(max_length=100)
    email2 = models.CharField(max_length=100)
    attempted_questions = models.CharField(max_length=1000)
    attempted_answers = models.CharField(max_length=1000)
    total_score = models.IntegerField(default=0)
    level = models.IntegerField(default=1)
    count_easy = models.IntegerField(default=0)
    count_medium = models.IntegerField(default=0)
    count_hard = models.IntegerField(default=0)
    question_array_easy = models.TextField()
    question_array_medium = models.TextField()
    question_array_hard = models.TextField()
    correct_answered = models.IntegerField(default=5)
    user_bonus_clicked = models.BooleanField(default=False)
    user_bonus_activated = models.BooleanField(default=True)
    end_time = models.IntegerField(default=0)

    def __str__(self):
        return str(self.pk)+" "+str(self.login_name)

comp/views.py
import simplejson as simplejson
from django.shortcuts import render, HttpResponse, render_to_response
from .models import Questions, User
import random
from operator import attrgetter
import json
import time
from subprocess import Popen, PIPE



def run_code():


    print("Thread started")

def register(request):

    data = json.load(open('main_comp_questions.json'))
    for i in data:
        new_question = Questions.objects.create(question=i['question'], option1=i['option1'], option2=i['option2'],
                                                option3=i['option3'], option4=i['option4'], answer=i['answer'], explanation='.')
        new_question.save()
    print("done==================")
    return render(request, 'comp/register_new.html')


def check_login(request):
    team_name = request.POST.get('team_name')
    participant1 = request.POST.get('participant1')
    mobile1 = request.POST.get('mobile1')
    college1 = request.POST.get('college1')
    email1 = request.POST.get('email1')
    reciept_number = request.POST.get('reciept_number')
    participant2 = request.POST.get('participant2')
    mobile2 = request.POST.get('mobile2')
    college2 = request.POST.get('college2')
    email2 = request.POST.get('email2')
    msg = ''
    new_user = User(login_name=team_name, receipt_number=reciept_number, phone_number1=mobile1, phone_number2=mobile2,
                    college_name1=college1,
                    college_name2=college2, user_name1=participant1, user_name2=participant2, email1=email1,
                    email2=email2)
    new_user.save()
    # return generate(request,new_user.pk)
    return instruction_view(request, new_user.pk)


# Generate once user registers
def generate(request, user_id):
    all_user = list(User.objects.all().order_by('total_score'))
    all_user.reverse()
    # try:
    #     f = open('requirement.txt', 'w')
    # 
    #     for user in all_user:
    #         code =str(user.user_name1 + " " + user.user_name2 + "  " + user.college_name1 + "  " + str(user.phone_number1) + "  "+ str(user.phone_number2)+ "  "+ str(user.total_score) +" \n\n ")#+ " " + user.user_name2 + " " + user.college_name1 + " " + user.phone_number1 + " " + user.phone_number2 + " " + user.total_score)
    # 
    #         f.write(code)
    #     f.close()
    # except:
    #     print("not")
    easy = [x + 1 for x in range(10)]
    random.shuffle(easy)
    medium = [x + 10 for x in range(10)]
    random.shuffle(medium)
    hard = [x + 20 for x in range(10)]
    random.shuffle(hard)
    # print(easy)
    # print(medium)
    # print(hard)
    # print(easy[0])
    current_user = User.objects.get(pk=user_id)

    current_user.question_array_easy = json.dumps(easy)
    current_user.question_array_medium = json.dumps(medium)
    current_user.question_array_hard = json.dumps(hard)
    current_user.count_easy = 0
    current_user.count_hard = 0
    current_user.count_medium = 0
    current_user.total_score = 0
    current_user.correct_answered = 3
    current_user.level = 1
    current_user.user_bonus_clicked = False
    current_user.user_bonus_activated = True
    current_user.end_time = time.time() + (20 * 60)
    # current_user.attempted_questions=easy[0]
    current_user.save()

    # return HttpResponse("<h3>hii</h3>")
    level = "Easy"
    all_user = list(User.objects.all().order_by('total_score'))
    all_user.reverse()

    return render(request, 'comp/question_new.html',
                  {'question': Questions.objects.get(pk=easy[0]), 'user_id': user_id, 'score': current_user.total_score,
                   'enabled_skip': True, 'enabled_bonus': True, 'remaining_time': '1800', 'level': level,
                   'all_user': all_user
                   }
                  )


# For next new Question or same Question if no option is selected
def next(request, user_id):
    if request.POST.get("finish_test"):
        all_user = list(User.objects.all().order_by('total_score'))
        all_user.reverse()
        # all_user = User.objects.all()
        # all_user.sort(key=lambda x: x.total_score(),reverse= True)
        # for user in all_user:
        # print(user.total_score)

        return render(request, 'comp/leaderboard_new.html', {'user_id': int(user_id), 'all_user': all_user})

    selected_option = request.POST.get("option")
    correct = False
    jsonDec = json.decoder.JSONDecoder()
    selected_id = request.POST.get("id")
    attempted_question = Questions.objects.get(pk=selected_id)
    # print(str(selected_option))
    # print(str(selected_id))
    counter = 0
    bonus_activated = False
    current_user = User.objects.get(pk=user_id)

    current_user.save()

    enabled_skip = False
    if current_user.correct_answered >= 3:
        enabled_skip = True

    if request.POST.get("bonus"):
        current_user.user_bonus_clicked = True
        current_user.save()
        level = ""
        if current_user.level == 1:
            level = "Easy"
        elif current_user.level == 2:
            level = "Medium"
        else:
            level = "Hard"

        all_user = User.objects.all().order_by('total_score').reverse()
        rank = 0
        for user in all_user:
            rank += 1
            if user == current_user:
                break
        return render(request, 'comp/question_new.html',
                      {'question': Questions.objects.get(pk=selected_id), 'user_id': user_id,
                       'enabled_skip': enabled_skip, 'enabled_bonus': False,
                       'score': current_user.total_score, 'current_rank': rank,
                       'remaining_time': current_user.end_time - time.time()})

    if request.POST.get("next"):
        # print(current_user.pk)
        # print(current_user.login_name)
        # print(current_user.attempted_questions)

        if selected_option in [None, '']:
            # print("inside none")
            # print(selected_id)
            # print(current_user.user_bonus)
            return render(request, 'comp/question_new.html',
                          {'question': Questions.objects.get(pk=selected_id), 'user_id': user_id,
                           'error_msg': 'Please select one option!', 'current_user': current_user,
                           'score': current_user.total_score, 'enabled_skip': enabled_skip,
                           'enabled_bonus': current_user.user_bonus_activated,
                           'remaining_time': current_user.end_time - time.time()})

        elif attempted_question.answer == selected_option:
            correct = True
            current_user.correct_answered += 1
            current_user.save()

        if attempted_question.option1 == selected_option:
            current_user.attempted_answers += ", 1"
        elif attempted_question.option2 == selected_option:
            current_user.attempted_answers += ", 2"
        elif attempted_question.option3 == selected_option:
            current_user.attempted_answers += ", 3"
        elif attempted_question.option4 == selected_option:
            current_user.attempted_answers += ", 4"
        current_user.attempted_questions += ("," + str(selected_id))
        current_user.save()

        if current_user.level == 1:
            current_user.count_easy += 1
            current_user.save()

            if correct is True:
                counter = current_user.count_medium
                question = jsonDec.decode(current_user.question_array_medium)
                current_user.level = 2
                current_user.total_score += 2
                level = "Medium"
                if current_user.user_bonus_clicked is True:
                    current_user.user_bonus_clicked = False
                    current_user.user_bonus_activated = False
                    bonus_activated = False
                    current_user.total_score += 2
                current_user.save()
            else:
                counter = current_user.count_easy
                current_user.total_score -= 1
                level = "Easy"
                if current_user.user_bonus_clicked is True:
                    current_user.user_bonus_clicked = False
                    current_user.user_bonus_activated = False
                    bonus_activated = False
                    current_user.total_score -= 1
                current_user.save()
                question = jsonDec.decode(current_user.question_array_easy)
        elif current_user.level == 2:
            # print("level 2")
            #
            # print(current_user.level)
            current_user.count_medium += 1
            current_user.save()
            if correct:
                level = "Hard"
                counter = current_user.count_hard
                question = jsonDec.decode(current_user.question_array_hard)
                current_user.level = 3
                current_user.total_score += 4
                if current_user.user_bonus_clicked is True:
                    current_user.user_bonus_clicked = False
                    current_user.user_bonus_activated = False
                    bonus_activated = False
                    current_user.total_score += 4
                current_user.save()
            else:
                level = "Easy"
                counter = current_user.count_easy
                question = jsonDec.decode(current_user.question_array_easy)
                current_user.level = 1
                current_user.total_score -= 2
                if current_user.user_bonus_clicked is True:
                    current_user.user_bonus_clicked = False
                    current_user.user_bonus_activated = False
                    bonus_activated = False
                    current_user.total_score -= 2
                current_user.save()
        else:
            # print("level 3")
            #
            # print(current_user.level)
            current_user.count_hard += 1
            current_user.save()

            if correct:
                level = "Hard"

comp/templates/comp/instructions.html
<html>
<head>

<style>


div {
background-color:#333333;
  margin-left: 20%;
margin-top: 0px;
margin-bottom: 150px;
 width: 65%;
border: 1px solid gray;
outline-color: black;
outline-style: groove;

}

body{background-image :url("black-abstract.jpg");
}

h1{text-align:center;
	font-size:300%;
}


input{
 text-align:right;

}
p{font-size:140%;

}
ol{
font-size:140%;
margin-left:100px;
margin-right:100px;
margin-top:10px;
margin-bottom:20px;
padding:0 0 0 0;
color:white;
font-family:sans-serif;
font-weight:normal;
}
</style>
</head>

<body>
<h1 style="color:white;"><b>INSTRUCTIONS</b></h1>

<div>
    <form action="{% url 'questions:generate' user_id %}" method="post">
        {% csrf_token %}
        {% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'comp/instruction.css' %}" />
<ol>
<p ><li> First round consists of MCQ which has 30 minutes as the time limit.</li><br><li>This Round consists of three levels which are Easy, Medium & Hard.<br>Each easy level question is for 2 marks,Medium level question is for 4 marks,Hard level question is for 8 marks.
</li><br><li>Each correct question will take you to higher level & Each wrong question will bring you to previous level.</li><br>
<li>There is negative marking for all questions.
<br>(+2,-1) for easy level question,(+4,-2) for medium level question, (+8,-4) for hard level question.
  </li> <br> <li> There are 2 lifelines in this level.<br>You can skip atmost 1 question if you don't know the answer and after answering 3 correct questions ,The skip option will get enabled automatically.</li>
<br><li>There is an option for BONUS which can be used only once.
<br>Clicking on that option will let you score the marks in following ways.<br> Marking scheme for different types of question are:-
<br>i. For easy level: (+4,-2)<br>ii. For Medium level: (+8,-4)<br>iii. For hard level: (+10,-8)</li>
</p>
<input  style="background-color:#666666;color:white; margin-left:95%" type="submit" id="submit"  value="Start Test">

</ol></form>
     </div>
</body>
</html>

comp/templates/comp/print_all_questions.html
<ul>
   {% for question in all_questions %}
    <li>{{question.pk}}  {{question.question}}</li>
   {% endfor %}


</ul>

comp/templates/comp/question.html
﻿
<html>
<form action="{% url 'questions:next' user_id %}" method="post" style="color: white">
    <head>
        <title>C-Storm </title>
        {% load static %}

        <link rel="stylesheet" type="text/css" href="{% static 'comp/style.css' %}"/>
        <style>

            h1 {
                color: #ffb499;
                font-family: "andalemono";
                margin-left: 35%;
                font-size: 200%;
            }

            div.container {
                width: 100%;
                background-color: transparent;
            }

            header {
                padding: 1em;
                color: white;
                background-color: #000033;
                clear: left;
                top: 0px;
                text-align: center;
            }

            input[type="submit"] {
                width = "50";
                height = "0.5";
                padding: 6px 17px;
                font-size: 20px;
                text-align: center;
                cursor: pointer;
                outline: none;
                color: #fff;
                background-color: #333333;
                border: none;
                border-radius: 10px;
            }

            input[type="submit"]:hover {
                background-color: #777777
            }

            button :active {
                display: inline-block;
                background-color: #333333;
                box-shadow: 0 5px #666;
                transform: translateY(4px);
            }

            #label1 {
                font-size: 125%;
                margin-left: 83%;
                text-align: center;
                background-color: #555555;

            }

            p {
                text-align: left;
                color: black;
                font-size: 27px;
            }

            hr {
                color: #D2B48C;
            }

            form {
                text-align: left;
                color: black;
                font-size: 23px;
                margin-left: 20px;
            }

            nav {
                float: left;
                max-width: 260px;
                margin: 0;
                padding: 1em;
            }

            article {
                margin-left: 10px;
                border-left: 1px solid gray;
                padding: 1em;
                overflow: hidden;
                background-color: transparent;
            }

            div {
                background-color: white;
                width: 1800px;
                border: 10px black;
                padding: 25px;

            }

            label {
                display: inline-block;
                width: 200px;

            }

            input[type="text"] {
                font-size: 20px;
                text-align: center;
                height: 50px;
                width: 200px;
            }
        </style>
    </head>


    {% csrf_token %}
    <body>
    <div class="container" style="padding:2px;">
        <nav>
            <ul>


                <!TIMMER code>

                <p style="font-size=200%; color: #ffb499"><b>TIME</b></p>

                <label type="label"
                       style="background-color:black;color:white;font-family:courier;font-size:250%;margin-top:-15px;margin-bottom:50px"
                       border="0"><b>
                    <span id="time1"></span></b>

                </label>

                <!Score code>

                <form style="color:white;margin-left:-5px" ;>
                    <label style="margin-top:-25px;color:#ffb499;font-size:150%;" for="readonly;"> SCORE </label><br>
                    <input name="readonly" type="text" value="{{ score }}" readonly>
                </form>

                <!LIFELINE code>
                <p style="font-size:150%;color:#ffb499">LIFE LINES</p>


                <input type="text" name="id" id="id" value="{{ question.pk }}" hidden>

                {% if enabled_bonus %}
                    <input type="submit"
                           style=
                                   "transition: .5s ease;
	margin-top:-50px;"

                           value="bonus" name="bonus"
                    />
                {% else %}
                    <input type="submit"
                           style=
                                   "transition: .5s ease;
	margin-top:-25px;"

                           value="bonus" name="bonus"
                           hidden disabled/>
                {% endif %}
                <br><br>
                <p id="demo"></p>

                {% if enabled_skip %}
                    <input type="submit" style=
                            "transition: .5s ease;
	margin-top:-25px;"

                           value="skip" name="skip"
                    />
                {% else %}
                    <input type="submit" style=
                            "transition: .5s ease;
	margin-top:-25px;"


                           value="skip" name="skip" hidden
                    />
                {% endif %}
                <p id="demo3"></p>

            </ul>


            </ul>

        </nav>

        <article>


            <h1>C-Storm </h1>
            <label id="label1">{{ level }}</label>

            <div style="background-color:#333333; margin-bottom:20px;">

                <pre>{{ question.question }}</pre>
            </div>

            {% for option in question.get_options %}
                <input type="radio" id="option{{ forloop.counter }}" name="option" value="{{ option }}"/>
                <label for="option{{ forloop.counter }}" class="control-label col-md-3 col-sm-3 col-xs-12"
                       style="background-color:#333333;width:95%;">
                    {{ option }}
                </label><br><br>
            {% endfor %}

            <input type="submit" style="position :relative;
	transition: .5s ease;"

                   value="next" name="next"/>


            <input type="submit" style="position :relative;
	transition: .5s ease;
	left:75%;"
                   value="Finish" name="finish_test"/>

            <p id="demo1"></p>

        </article>
    </div>
    </body>

    <script type="text/javascript">

        function startTimer(duration, display) {
            var start = Date.now(),

                diff,
                minutes,
                seconds;

            function timer() {
                // get the number of seconds that have elapsed since
                // startTimer() was called
                diff = duration - (((Date.now() - start) / 1000) | 0);

                // does the same job as parseInt truncates the float
                minutes = (diff / 60) | 0;
                seconds = (diff % 60) | 0;

                minutes = minutes < 10 ? "0" + minutes : minutes;
                seconds = seconds < 10 ? "0" + seconds : seconds;

                display.textContent = minutes + ":" + seconds;


                if (diff <= 0) {
                    // add one second so that the count down starts at the full duration
                    // example 05:00 not 04:59
                    // start = Date.now() + 1000;
                    // window.location.replace("http:/comp/leaderboard/" );
                    window.location.replace(" {%url 'questions:leaderboard' user_id %}");
                }

            };
            // we don't want to wait a full second before the timer starts
            timer();
            setInterval(timer, 1000);
        }

        window.onload = function () {
            var v = "{{remaining_time}}";

            display = document.querySelector('#time1');
            startTimer(v, display);
        };
    </script>


</form>

</html>

comp/templates/comp/question_new.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Questions | EarnCode</title>

    <link href="{% static '/comp/css/font.css' %}" rel="stylesheet">
    <script src="{% static '/comp/js/jquery.min.js' %}"></script>
    <link rel="stylesheet"
          href="{% static '/comp/css/jquery-ui.min.css' %}">
    <script src="{% static '/comp/js/jquery-ui.min.js' %}"></script>

    <link rel="stylesheet" href="{% static '/comp/css/bootstrap.min.css' %}">


    <script src="{% static '/comp/js/bootstrap.min.js' %}"></script>
    <style>
        html, body {
            background: #fff;
            font-family: 'Roboto', sans-serif;
        }

        legend {
            color: #0379C4;
        }

        .table-responsive {
            max-height: 400px;
        }
    </style>
</head>

<body>

<form action="{% url 'questions:next' user_id %}" method="post">
    {% csrf_token %}
    <div class="container">
        {#        <div class="row text-center">#}
        {#            <h1>EarnCode</h1>#}
        {#        </div>#}
        <div class="row">
            <div class="col-md-4">
                <div class="row">
                    <h4>TIMER</h4>
                </div>
                <div class="row">
                    <h3 id="time" style="border: 1px solid black; padding: 2.5%; width: 22%;">timer</h3>
                </div>
            </div>
            <div class="col-md-4 col-md-offset-4 text-right">
                <div class="row">
                    <h4>SCORE</h4>
                </div>
                <div class="row">
                    <h3><strong style="border: 1px solid black; padding: 2.5%">{{ score }}</strong></h3>
                </div>
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-4">
                <h3>{{ level }}</h3>
            </div>
            <div class="col-md-4"></div>
            <div class="col-md-4 text-right">
                <div class="col-md-4">
                    <h3 style="margin-top: 5px;">LIFELINES</h3>
                </div>

                <div class="col-md-4">
                    {% if enabled_bonus %}
                        <input class="btn btn-info" type="submit" value="Bonus" name="bonus"/>
                    {% else %}
                        <input type="submit" value="Bonus" name="bonus" disabled hidden/>
                    {% endif %}
                </div>
                <div class="col-md-4">
                    {% if enabled_skip %}
                        <input class="btn btn-danger" type="submit" value="Skip" name="skip"/>
                    {% else %}
                        <input class="btn" type="submit" value="Skip" name="skip" disabled/>
                    {% endif %}
                </div>
                <input type="text" name="id" id="id" value="{{ question.pk }}" hidden>

            </div>
        </div>
        <div class="row">
            <div class="col-md-8">
                <div class="row">
                    <pre>{{ question.question }}</pre>
                </div>
                <div class="row">
                    {% for option in question.get_options %}
                        <input type="radio" id="option{{ forloop.counter }}" name="option" value="{{ option }}"/>
                        <label for="option{{ forloop.counter }}" class="control-label">
                            {{ option }}
                        </label>
                        <br>
                        <br>

                    {% endfor %}
                </div>
                <div class="row text-center ">
                    <div class="col-md-2 col-md-offset-3">
                        <input class="btn btn-primary" type="submit" value="Next" name="next">
                    </div>
                    <div class="col-md-2 col-md-offset-2">
                        <input class="btn btn-success" type="submit" value="Finish" name="finish_test"/>
                    </div>
                </div>
            </div>
            <div class="col-md-4">

                Leaderboard: Your Rank: <label id="current_rank">{{ current_rank }}</label>
                <div class="table-responsive">
                    <table class="table table-bordered white">
                        <thead class="thead-inverse">

                        <tr>


                            <th>Rank</th>
                            <th>Team Name</th>
                            <th>Score</th>
                        </tr>
                        </thead>
                        <tbody id="table_body">
                        {% for user in all_user %}
                            {% ifequal user_id user.pk %}
                            <tr bgcolor="#BBBBBB" style="color:#000000">
                                {% else %}
                            <tr>
                            {% endifequal %}
                                <td>{{ forloop.counter }}</td>
                                <td>{{ user.login_name }}</td>
                                <td>{{ user.total_score }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</form>
</body>
<script>
    function startTimer(duration, display) {
        var start = Date.now(),
            diff,
            minutes,
            seconds;

        function timer() {
            // get the number of seconds that have elapsed since
            // startTimer() was called
            diff = duration - (((Date.now() - start) / 1000) | 0);
            // does the same job as parseInt truncates the float
            minutes = (diff / 60) | 0;
            seconds = (diff % 60) | 0;
            minutes = minutes < 10 ? "0" + minutes : minutes;
            seconds = seconds < 10 ? "0" + seconds : seconds;
            display.textContent = minutes + ":" + seconds;
            if (diff <= 0) {
                // add one second so that the count down starts at the full duration
                // example 05:00 not 04:59
                // start = Date.now() + 1000;
                // window.location.replace("http:/comp/leaderboard/" );
                window.location.replace(" {%url 'questions:leaderboard' user_id %}");
            }
        };
        // we don't want to wait a full second before the timer starts
        timer();
        setInterval(timer, 1000);
    }

    window.onload = function () {
        var v = "{{remaining_time}}";
        display = document.querySelector('#time');
        startTimer(v, display);
    };
</script>

<script>
    $(document).ready(function update() {
        $.ajax({
            type: "POST",
            url: "{% url 'questions:update_leaderboard' %}",
            data: {
                csrfmiddlewaretoken: '{{ csrf_token }}'
            },
            success: function (data) {
                let parsed = JSON.parse(data);
                {#alert();#}
                {#let parsed = JSON.parse(data);#}
                {#alert(parsed.read);#}
                let table_body = document.getElementById('table_body');
                while (table_body.firstChild) {
                    table_body.removeChild(table_body.firstChild);
                }
                c = 1;
                for (let i in parsed.read) {
                    let row = document.createElement('tr');
                    let column = document.createElement('td');
                    column.innerHTML = c++;
                    row.appendChild(column);
                    column = document.createElement('td');
                    column.innerHTML = parsed.read[i];
                    row.appendChild(column);
                    column = document.createElement('td');
                    column.innerHTML = parsed.newest[i];
                    row.appendChild(column);
                    table_body.appendChild(row);
                    {#alert({{ current_user.login_name }});#}
                    if ("{{ current_team }}" === parsed.read[i]) {
                        row.style.backgroundColor = "gray";
                    }
                }
            },
            complete: function () {
                // Schedule the next request when the current one's complete
                setTimeout(update, 5000);
            }
        });
        return false; //<---- move it here
    });
</script>

</html>